### ISSUE TITLE
Uncaught exception building open source project

### ISSUE THREAD

**Issue by iamleeg** [gnustep/tools-buildtool#1]
Steps to reproduce:

1. clone [AntiRSI](https://github.com/srbaker/AntiRSI)
2. checkout commit ece90a21e4560e7201a0060e7176ba39447ad747 (probably other commits too, this one definitely exhibits it)
3. `buildtool`

You get an uncaught exception about being unable to determine the type information for `[NSConstantString count]`, which is unsurprising as that isn't a good selector. This occurs during the compilation step for `main.m` which is the first file in the "Compile Sources" build phase, but definitely before invoking the compiler. Unfortunately as this seems to be in an FFI trampoline I couldn't get a backtrace from gdb to investigate further.

P.S. We know that the project won't build on GNUstep _anyway_ due to using APIs that are Mac-only, but it would be good to at least get to the real compile errors with `buildtool` :).

**Comment by gcasa** [comment]
Hey Graham.  I am going to take a look at this ASAP.  I just noticed the issue you submitted.

**Comment by gcasa** [comment]
Fixed the uncaught exception, but there is another issue with copying the nib.  The problem was that some constants in the XCODE project can be "" instead of an NSArray when empty (apparently).  Also, there is a missing framework called "ApplicationSupport" which isn't present in GNUstep that is required by the project you specified.  Hopefully, the dependency is not that deep, so it may be possible to work around it.

**Comment by iamleeg** [comment]
Thanks @gcasa, I expected that `ApplicationSupport` would be missing and I think it's possible to remove the dependency completely from a port, but if you've got as far as the Link Libraries phase it means the build phase is working!
